// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fphiroahxgkjxcqvtimj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZwaGlyb2FoeGdranhjcXZ0aW1qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2Mjk4NjcsImV4cCI6MjA1ODIwNTg2N30.Fxywp4A5FWCok8_-vOiuVuzDbcxwknOWZxK7IPicIhw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);